// Generated by https://quicktype.io

export interface UserI {
    id?:       string;
    username: string;
    email:    string;
    password: string;
    rolName:  string;
    // profile:  Profile;
    // routines: Routine[];
}

// export interface Profile {
//     id:     string;
//     age:    number;
//     weight: number;
//     height: number;
//     imc:    number;
// }

// export interface Routine {
//     id:      string;
//     date:    string;
//     horario: string;
//     product: Product;
// }

// export interface Product {
//     id:          string;
//     productName: string;
//     calories:    number;
//     carbs:       number;
//     category:    Category;
// }

// export interface Category {
//     id:           string;
//     categoryName: string;
// }
