

// Generated by https://quicktype.io

import { ProductResponeI } from "..";

export interface RoutineResponseI {
    id:      string;
    date:    string;
    horario: string;
    product: ProductResponeI;
}




export interface CreateRoutineI {
    userId:    string;
    productId: string;
    date:      string;
    horario:   string;
}
