// Generated by https://quicktype.io

import { CategoryResponseI } from "..";

export interface ProductResponeI {
    id:          string;
    productName: string;
    calories:    number;
    carbs:       number;
    category:    CategoryResponseI;
}


